### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by neripark** [neripark/sls-cron-playground#1]
とりあえずDeployは成功したので。

- [x] 時刻変更してみる
- [x] lighthouse 実行させる。（local）
- [ ] 容量が大きいのでS3でlayler使う
- [ ] lighthouse 実行させる。（AWS）
- [ ] ディレクトリ構成をエンドポイントで分けたい
- [ ] TypeScript 入れる（自前でビルドしてもいいかも）
